CREATE TABLE merchants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    webhook    VARCHAR(255)                            NOT NULL,
    tax_number VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    login      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_merchants PRIMARY KEY (id)
);

ALTER TABLE merchants
    ADD CONSTRAINT uc_merchants_taxnumber UNIQUE (tax_number);