CREATE SEQUENCE IF NOT EXISTS merchant_entity_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS notification_entity_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE merchant_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_name VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    login        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    tax_number   VARCHAR(255)                            NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    webhook      VARCHAR(255)                            NOT NULL,
    CONSTRAINT merchant_entity_pkey PRIMARY KEY (id)
);

CREATE TABLE notification_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content     VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    receiver    VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    merchant_id BIGINT,
    CONSTRAINT notification_entity_pkey PRIMARY KEY (id)
);

ALTER TABLE merchant_entity
    ADD CONSTRAINT ukiwfoa8qdqf1d0ugijri1lv2o2 UNIQUE (tax_number);

ALTER TABLE notification_entity
    ADD CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchant_entity (id) ON DELETE NO ACTION;